/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Session { 'date' : bigint, 'durationMinutes' : bigint }
export interface Task {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'completed' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<[string], undefined>,
  'askQuestion' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeStudySession' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentStreak' : ActorMethod<[], bigint>,
  'getRandomQuote' : ActorMethod<[], string>,
  'getSessionHistory' : ActorMethod<[], Array<Session>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'toggleTaskComplete' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];